// Package di owns the backend's dependency-injection graph. The service
// construction order is generated by google/wire (see wire.go / wire_gen.go);
// this file holds the aggregate Services container and the small set of
// provider wrappers wire cannot synthesize on its own.
package di

import (
	"context"
	"embed"
	"log/slog"
	"net/http"

	"github.com/getarcaneapp/arcane/backend/internal/config"
	"github.com/getarcaneapp/arcane/backend/internal/database"
	"github.com/getarcaneapp/arcane/backend/internal/middleware"
	"github.com/getarcaneapp/arcane/backend/internal/services"
	pkg_scheduler "github.com/getarcaneapp/arcane/backend/pkg/scheduler"
	"github.com/getarcaneapp/arcane/backend/resources"
)

// Services is the single aggregate of every constructed service. wire populates
// every field via wire.Struct(new(Services), "*"); it is the only service
// container in the backend (handlers, jobs, and the router all read from it).
type Services struct {
	AppImages         *services.ApplicationImagesService
	User              *services.UserService
	Project           *services.ProjectService
	Environment       *services.EnvironmentService
	Settings          *services.SettingsService
	KV                *services.KVService
	JobSchedule       *services.JobService
	SettingsSearch    *services.SettingsSearchService
	CustomizeSearch   *services.CustomizeSearchService
	Container         *services.ContainerService
	Image             *services.ImageService
	Build             *services.BuildService
	BuildWorkspace    *services.BuildWorkspaceService
	Volume            *services.VolumeService
	Network           *services.NetworkService
	Port              *services.PortService
	Swarm             *services.SwarmService
	ImageUpdate       *services.ImageUpdateService
	Session           *services.SessionService
	Auth              *services.AuthService
	Oidc              *services.OidcService
	Docker            *services.DockerClientService
	Template          *services.TemplateService
	ContainerRegistry *services.ContainerRegistryService
	System            *services.SystemService
	SystemUpgrade     *services.SystemUpgradeService
	Diagnostics       *services.DiagnosticsService
	Updater           *services.UpdaterService
	Event             *services.EventService
	Activity          *services.ActivityService
	Version           *services.VersionService
	Notification      *services.NotificationService
	ApiKey            *services.ApiKeyService
	Federated         *services.FederatedCredentialService
	GitRepository     *services.GitRepositoryService
	GitOpsSync        *services.GitOpsSyncService
	Webhook           *services.WebhookService
	Vulnerability     *services.VulnerabilityService
	Dashboard         *services.DashboardService
	Role              *services.RoleService
	// AuthMiddleware is the shared Echo auth middleware. It's wired here so the
	// router consumes it from the container instead of building the chain inline.
	AuthMiddleware *middleware.AuthMiddleware
}

// DockerClient returns the Docker client service. Bootstrap needs the docker
// service on its own (for Close and startup state) before the rest of the
// container is consumed; this avoids a second return value from the injector.
func (s *Services) DockerClient() *services.DockerClientService {
	return s.Docker
}

// provideResourcesFSInternal exposes the embedded resource filesystem to the graph so
// wire can call services.NewApplicationImagesService directly.
func provideResourcesFSInternal() embed.FS {
	return resources.FS
}

// The following wrappers exist only because wire cannot synthesize these
// constructors by type: they read scalar fields/package vars off the config,
// take parameters of unexported interface types, or apply a post-construction
// builder. Keeping them here (in the untagged file) lets the generated
// wire_gen.go call them in a normal build.

// provideVersionServiceInternal supplies the bool/string scalars wire can't inject by type.
func provideVersionServiceInternal(httpClient *http.Client, cfg *config.Config, registry *services.ContainerRegistryService, docker *services.DockerClientService, imageUpdate *services.ImageUpdateService) *services.VersionService {
	return services.NewVersionService(httpClient, cfg.UpdateCheckDisabled, config.Version, config.Revision, registry, docker, imageUpdate)
}

// provideGitRepositoryServiceInternal supplies cfg.GitWorkDir (bare string).
func provideGitRepositoryServiceInternal(db *database.DB, cfg *config.Config, event *services.EventService, settings *services.SettingsService) *services.GitRepositoryService {
	return services.NewGitRepositoryService(db, cfg.GitWorkDir, event, settings)
}

// provideVolumeServiceInternal supplies cfg.BackupVolumeName (bare string).
func provideVolumeServiceInternal(db *database.DB, docker *services.DockerClientService, event *services.EventService, settings *services.SettingsService, container *services.ContainerService, image *services.ImageService, cfg *config.Config) *services.VolumeService {
	return services.NewVolumeService(db, docker, event, settings, container, image, cfg.BackupVolumeName)
}

// provideAuthServiceInternal supplies cfg.JWTSecret (bare string).
func provideAuthServiceInternal(user *services.UserService, settings *services.SettingsService, event *services.EventService, session *services.SessionService, role *services.RoleService, cfg *config.Config) *services.AuthService {
	return services.NewAuthService(user, settings, event, session, role, cfg.JWTSecret, cfg)
}

// provideContainerRegistryServiceInternal builds the registryDaemonGetter closure from
// the docker service. registryDaemonGetter is unexported, so wire can't name it.
func provideContainerRegistryServiceInternal(db *database.DB, docker *services.DockerClientService, kv *services.KVService) *services.ContainerRegistryService {
	return services.NewContainerRegistryService(db, func(ctx context.Context) (services.RegistryDaemonClient, error) {
		return docker.GetClient(ctx)
	}, kv)
}

func provideProjectServiceInternal(db *database.DB, settings *services.SettingsService, event *services.EventService, image *services.ImageService, docker *services.DockerClientService, build *services.BuildService, environment *services.EnvironmentService, cfg *config.Config) *services.ProjectService {
	return services.NewProjectService(db, settings, event, image, docker, build, cfg).
		WithRegistryCredentialsProvider(environment.GetEnabledRegistryCredentials)
}

// provideUpdaterServiceInternal passes *SystemUpgradeService for the unexported
// selfUpgradeService parameter so wire never sees the unexported type.
func provideUpdaterServiceInternal(db *database.DB, settings *services.SettingsService, docker *services.DockerClientService, project *services.ProjectService, imageUpdate *services.ImageUpdateService, registry *services.ContainerRegistryService, event *services.EventService, image *services.ImageService, notification *services.NotificationService, systemUpgrade *services.SystemUpgradeService, activity *services.ActivityService) *services.UpdaterService {
	return services.NewUpdaterService(db, settings, docker, project, imageUpdate, registry, event, image, notification, systemUpgrade, activity)
}

// provideUserServiceInternal applies the RoleService builder. The builder stays on the
// type for tests; wire calls this wrapper.
func provideUserServiceInternal(db *database.DB, role *services.RoleService) *services.UserService {
	return services.NewUserService(db).WithRoleService(role)
}

// provideApiKeyServiceInternal applies the RoleService builder.
func provideApiKeyServiceInternal(db *database.DB, user *services.UserService, role *services.RoleService) *services.ApiKeyService {
	return services.NewApiKeyService(db, user).WithRoleService(role)
}

// provideFederatedCredentialServiceInternal applies the RoleService builder.
func provideFederatedCredentialServiceInternal(db *database.DB, auth *services.AuthService, user *services.UserService, settings *services.SettingsService, event *services.EventService, httpClient *http.Client, role *services.RoleService) *services.FederatedCredentialService {
	return services.NewFederatedCredentialService(db, auth, user, settings, event, httpClient).WithRoleService(role)
}

// provideAuthMiddlewareInternal builds the shared Echo auth middleware. The builder
// methods take interfaces (ApiKeyValidator / EnvironmentAccessTokenResolver /
// PermissionResolver) that the concrete services already satisfy.
func provideAuthMiddlewareInternal(auth *services.AuthService, apiKey *services.ApiKeyService, env *services.EnvironmentService, role *services.RoleService, cfg *config.Config) *middleware.AuthMiddleware {
	return middleware.NewAuthMiddleware(auth, cfg).
		WithApiKeyValidator(apiKey).
		WithEnvironmentAccessTokenResolver(env).
		WithPermissionResolver(role)
}

// Jobs aggregates every scheduler job. wire populates it via wire.Struct; the
// bootstrap then registers the constructed jobs with the scheduler and wires the
// settings-change callbacks — those are post-construction concerns wire does not handle.
type Jobs struct {
	AutoUpdate             *pkg_scheduler.AutoUpdateJob
	ImagePolling           *pkg_scheduler.ImagePollingJob
	DockerClientRefresh    *pkg_scheduler.DockerClientRefreshJob
	Analytics              *pkg_scheduler.AnalyticsJob
	EventCleanup           *pkg_scheduler.EventCleanupJob
	PruningVolumeHelper    *pkg_scheduler.PruningVolumeHelperJob
	ExpiredSessionsCleanup *pkg_scheduler.ExpiredSessionsCleanupJob
	ScheduledPrune         *pkg_scheduler.ScheduledPruneJob
	FilesystemWatcher      *pkg_scheduler.FilesystemWatcherJob
	VulnerabilityScan      *pkg_scheduler.VulnerabilityScanJob
	AutoHeal               *pkg_scheduler.AutoHealJob
}

// provideAnalyticsJobInternal preserves the existing nil http.Client (the analytics job
// builds its own default client when none is supplied).
func provideAnalyticsJobInternal(settings *services.SettingsService, kv *services.KVService, cfg *config.Config) *pkg_scheduler.AnalyticsJob {
	return pkg_scheduler.NewAnalyticsJob(settings, kv, nil, cfg)
}

// provideFilesystemWatcherJobInternal supplies ctx + cfg.ProjectScanMaxDepth and keeps the
// watcher-setup failure non-fatal (logged; a nil job is tolerated downstream), matching
// the previous bootstrap behavior.
func provideFilesystemWatcherJobInternal(ctx context.Context, project *services.ProjectService, template *services.TemplateService, settings *services.SettingsService, cfg *config.Config) *pkg_scheduler.FilesystemWatcherJob {
	job, err := pkg_scheduler.RegisterFilesystemWatcherJob(ctx, project, template, settings, cfg.ProjectScanMaxDepth)
	if err != nil {
		slog.ErrorContext(ctx, "Failed to register filesystem watcher job", "error", err)
	}
	return job
}
