// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/getarcaneapp/arcane/backend/internal/config"
	"github.com/getarcaneapp/arcane/backend/internal/database"
	"github.com/getarcaneapp/arcane/backend/internal/services"
	"github.com/getarcaneapp/arcane/backend/pkg/scheduler"
	"github.com/google/wire"
	"net/http"
)

// Injectors from wire.go:

// InitializeServices builds the full service graph. ctx, db, cfg, and httpClient
// are graph inputs supplied by the caller; every other value is constructed by
// ServiceSet. The generated implementation lives in wire_gen.go.
func InitializeServices(ctx context.Context, db *database.DB, cfg *config.Config, httpClient *http.Client) (*Services, error) {
	fs := provideResourcesFSInternal()
	settingsService, err := services.NewSettingsService(ctx, db)
	if err != nil {
		return nil, err
	}
	applicationImagesService := services.NewApplicationImagesService(fs, settingsService)
	roleService := services.NewRoleService(db)
	userService := provideUserServiceInternal(db, roleService)
	eventService := services.NewEventService(db, cfg, httpClient)
	dockerClientService := services.NewDockerClientService(ctx, db, cfg, settingsService)
	kvService := services.NewKVService(db)
	containerRegistryService := provideContainerRegistryServiceInternal(db, dockerClientService, kvService)
	apiKeyService := provideApiKeyServiceInternal(db, userService, roleService)
	environmentService := services.NewEnvironmentService(db, httpClient, dockerClientService, eventService, settingsService, apiKeyService)
	notificationService := services.NewNotificationService(db, cfg, environmentService)
	activityService := services.NewActivityService(db)
	imageUpdateService := services.NewImageUpdateService(db, settingsService, containerRegistryService, dockerClientService, eventService, notificationService, activityService)
	vulnerabilityService := services.NewVulnerabilityService(db, dockerClientService, eventService, settingsService, notificationService, activityService, containerRegistryService)
	imageService := services.NewImageService(db, dockerClientService, containerRegistryService, imageUpdateService, vulnerabilityService, eventService)
	gitRepositoryService := provideGitRepositoryServiceInternal(db, cfg, eventService, settingsService)
	buildService := services.NewBuildService(db, settingsService, dockerClientService, containerRegistryService, gitRepositoryService, eventService)
	projectService := provideProjectServiceInternal(db, settingsService, eventService, imageService, dockerClientService, buildService, environmentService, cfg)
	jobService := services.NewJobService(db, settingsService, cfg)
	settingsSearchService := services.NewSettingsSearchService()
	customizeSearchService := services.NewCustomizeSearchService()
	containerService := services.NewContainerService(ctx, db, eventService, dockerClientService, imageService, settingsService, projectService)
	buildWorkspaceService := services.NewBuildWorkspaceService(settingsService)
	volumeService := provideVolumeServiceInternal(db, dockerClientService, eventService, settingsService, containerService, imageService, cfg)
	networkService := services.NewNetworkService(db, dockerClientService, eventService)
	portService := services.NewPortService(dockerClientService)
	swarmService := services.NewSwarmService(dockerClientService, settingsService, kvService, containerRegistryService, environmentService)
	sessionService := services.NewSessionService(db)
	authService := provideAuthServiceInternal(userService, settingsService, eventService, sessionService, roleService, cfg)
	oidcService := services.NewOidcService(authService, settingsService, cfg, httpClient)
	templateService := services.NewTemplateService(ctx, db, httpClient, settingsService)
	systemService := services.NewSystemService(db, dockerClientService, containerService, imageService, volumeService, networkService, settingsService, activityService)
	versionService := provideVersionServiceInternal(httpClient, cfg, containerRegistryService, dockerClientService, imageUpdateService)
	systemUpgradeService := services.NewSystemUpgradeService(dockerClientService, versionService, eventService, settingsService)
	diagnosticsService := services.NewDiagnosticsService()
	updaterService := provideUpdaterServiceInternal(db, settingsService, dockerClientService, projectService, imageUpdateService, containerRegistryService, eventService, imageService, notificationService, systemUpgradeService, activityService)
	federatedCredentialService := provideFederatedCredentialServiceInternal(db, authService, userService, settingsService, eventService, httpClient, roleService)
	gitOpsSyncService := services.NewGitOpsSyncService(db, gitRepositoryService, projectService, swarmService, eventService, settingsService)
	webhookService := services.NewWebhookService(db, containerService, updaterService, projectService, gitOpsSyncService, eventService)
	dashboardService := services.NewDashboardService(db, dockerClientService, containerService, projectService, imageService, settingsService, vulnerabilityService, environmentService, versionService)
	authMiddleware := provideAuthMiddlewareInternal(authService, apiKeyService, environmentService, roleService, cfg)
	diServices := &Services{
		AppImages:         applicationImagesService,
		User:              userService,
		Project:           projectService,
		Environment:       environmentService,
		Settings:          settingsService,
		KV:                kvService,
		JobSchedule:       jobService,
		SettingsSearch:    settingsSearchService,
		CustomizeSearch:   customizeSearchService,
		Container:         containerService,
		Image:             imageService,
		Build:             buildService,
		BuildWorkspace:    buildWorkspaceService,
		Volume:            volumeService,
		Network:           networkService,
		Port:              portService,
		Swarm:             swarmService,
		ImageUpdate:       imageUpdateService,
		Session:           sessionService,
		Auth:              authService,
		Oidc:              oidcService,
		Docker:            dockerClientService,
		Template:          templateService,
		ContainerRegistry: containerRegistryService,
		System:            systemService,
		SystemUpgrade:     systemUpgradeService,
		Diagnostics:       diagnosticsService,
		Updater:           updaterService,
		Event:             eventService,
		Activity:          activityService,
		Version:           versionService,
		Notification:      notificationService,
		ApiKey:            apiKeyService,
		Federated:         federatedCredentialService,
		GitRepository:     gitRepositoryService,
		GitOpsSync:        gitOpsSyncService,
		Webhook:           webhookService,
		Vulnerability:     vulnerabilityService,
		Dashboard:         dashboardService,
		Role:              roleService,
		AuthMiddleware:    authMiddleware,
	}
	return diServices, nil
}

// InitializeJobs constructs all scheduler jobs from the built services. The caller
// registers them with the scheduler and wires the settings-change callbacks.
func InitializeJobs(ctx context.Context, cfg *config.Config, svcs *Services) *Jobs {
	updaterService := svcs.Updater
	settingsService := svcs.Settings
	autoUpdateJob := scheduler.NewAutoUpdateJob(updaterService, settingsService)
	imageUpdateService := svcs.ImageUpdate
	environmentService := svcs.Environment
	imagePollingJob := scheduler.NewImagePollingJob(imageUpdateService, settingsService, environmentService)
	dockerClientService := svcs.Docker
	dockerClientRefreshJob := scheduler.NewDockerClientRefreshJob(dockerClientService, settingsService)
	kvService := svcs.KV
	analyticsJob := provideAnalyticsJobInternal(settingsService, kvService, cfg)
	eventService := svcs.Event
	activityService := svcs.Activity
	eventCleanupJob := scheduler.NewEventCleanupJob(eventService, activityService, settingsService)
	volumeService := svcs.Volume
	pruningVolumeHelperJob := scheduler.NewPruningVolumeHelperJob(volumeService, settingsService)
	sessionService := svcs.Session
	expiredSessionsCleanupJob := scheduler.NewExpiredSessionsCleanupJob(sessionService, settingsService)
	systemService := svcs.System
	notificationService := svcs.Notification
	scheduledPruneJob := scheduler.NewScheduledPruneJob(systemService, settingsService, notificationService)
	projectService := svcs.Project
	templateService := svcs.Template
	filesystemWatcherJob := provideFilesystemWatcherJobInternal(ctx, projectService, templateService, settingsService, cfg)
	vulnerabilityService := svcs.Vulnerability
	vulnerabilityScanJob := scheduler.NewVulnerabilityScanJob(vulnerabilityService, settingsService)
	autoHealJob := scheduler.NewAutoHealJob(dockerClientService, settingsService, eventService, notificationService)
	jobs := &Jobs{
		AutoUpdate:             autoUpdateJob,
		ImagePolling:           imagePollingJob,
		DockerClientRefresh:    dockerClientRefreshJob,
		Analytics:              analyticsJob,
		EventCleanup:           eventCleanupJob,
		PruningVolumeHelper:    pruningVolumeHelperJob,
		ExpiredSessionsCleanup: expiredSessionsCleanupJob,
		ScheduledPrune:         scheduledPruneJob,
		FilesystemWatcher:      filesystemWatcherJob,
		VulnerabilityScan:      vulnerabilityScanJob,
		AutoHeal:               autoHealJob,
	}
	return jobs
}

// wire.go:

// ServiceSet is the single, central provider set for the whole backend. Every
// service constructor (or the wrapper it requires) is listed here exactly once;
// wire derives the construction order from the dependency graph, so ordering is
// no longer maintained by hand. wire.Struct assembles the aggregate Services.
var ServiceSet = wire.NewSet(

	provideResourcesFSInternal, services.NewEventService, services.NewActivityService, services.NewSettingsService, services.NewKVService, services.NewJobService, services.NewSettingsSearchService, services.NewCustomizeSearchService, services.NewApplicationImagesService, services.NewDockerClientService, services.NewRoleService, services.NewSessionService, services.NewEnvironmentService, services.NewNotificationService, services.NewVulnerabilityService, services.NewImageUpdateService, services.NewImageService, services.NewBuildService, services.NewBuildWorkspaceService, provideProjectServiceInternal, services.NewContainerService, services.NewDashboardService, services.NewNetworkService, services.NewPortService, services.NewSwarmService, services.NewTemplateService, services.NewOidcService, services.NewSystemService, services.NewSystemUpgradeService, services.NewDiagnosticsService, services.NewGitOpsSyncService, services.NewWebhookService, provideVersionServiceInternal,
	provideGitRepositoryServiceInternal,
	provideVolumeServiceInternal,
	provideAuthServiceInternal,
	provideContainerRegistryServiceInternal,
	provideUpdaterServiceInternal,
	provideUserServiceInternal,
	provideApiKeyServiceInternal,
	provideFederatedCredentialServiceInternal,

	provideAuthMiddlewareInternal, wire.Struct(new(Services), "*"),
)

// JobSet builds every scheduler job from an already-constructed *Services (whose
// fields are exposed to the graph via wire.FieldsOf) plus the app context and config.
var JobSet = wire.NewSet(wire.FieldsOf(new(*Services),
	"Updater", "Settings", "ImageUpdate", "Environment", "Docker", "KV",
	"Event", "Activity", "Session", "System", "Notification", "Project",
	"Template", "Vulnerability", "Volume",
), scheduler.NewAutoUpdateJob, scheduler.NewImagePollingJob, scheduler.NewDockerClientRefreshJob, provideAnalyticsJobInternal, scheduler.NewEventCleanupJob, scheduler.NewPruningVolumeHelperJob, scheduler.NewExpiredSessionsCleanupJob, scheduler.NewScheduledPruneJob, provideFilesystemWatcherJobInternal, scheduler.NewVulnerabilityScanJob, scheduler.NewAutoHealJob, wire.Struct(new(Jobs), "*"),
)
