version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
    patterns: ["*"]
    cooldown:
      default-days: 2
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "17:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/"
    patterns: ["*"]
    cooldown:
      default-days: 2
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "17:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    cooldown:
      default-days: 2
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "17:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/docker"
    patterns: ["*"]
    cooldown:
      default-days: 2
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "17:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "devcontainers"
    directory: "/"
    patterns: ["*"]
    cooldown:
      default-days: 2
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "17:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"
