version: 2
multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "17:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"

updates:
  - package-ecosystem: "npm"
    directories:
      - "/frontend"
      - "/tests"
      - "/email-templates"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
    versioning-strategy: "increase-if-necessary"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    cooldown:
      default-days: 2

  - package-ecosystem: "gomod"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    cooldown:
      default-days: 2

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    cooldown:
      default-days: 2

  - package-ecosystem: "docker"
    directory: "/docker"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    cooldown:
      default-days: 2

  - package-ecosystem: "devcontainers"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    cooldown:
      default-days: 2
