ARG ARCANE_RUNTIME_BASE_IMAGE=ghcr.io/getarcaneapp/base:distroless
FROM ${ARCANE_RUNTIME_BASE_IMAGE}

ARG TARGETPLATFORM

WORKDIR /app

COPY ${TARGETPLATFORM}/arcane-agent ./arcane-agent

ENV ENVIRONMENT=production \
    AGENT_MODE=true \
    GIN_MODE=release \
    PORT=3553

# The container starts as "root", but arcane drops to the requetsed PUID and PGID after the runtime is initialized 
USER 0:0
EXPOSE 3553
VOLUME ["/app/data"]

CMD ["./arcane-agent"]
